---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: williamkhoo-sa
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: williamkhoo-sa

---
apiVersion: v1
kind: Secret
metadata:
  name: williamkhoo-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: williamkhoo-sa
type: kubernetes.io/service-account-token