# Service Account with Full Namespace Access
# Replace 'my-namespace' with your target namespace
# Replace 'my-service-account' with your desired service account name

---
# Namespace (optional - create if it doesn't exist)
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: my-namespace
  labels:
    app: my-service-account
automountServiceAccountToken: true

---
# Role with full permissions in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-service-account-role
  namespace: my-namespace
rules:
  # Full access to all resources in the namespace
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  # Core resources
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  # Apps
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  # Extensions
  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["*"]
  # Networking
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  # Storage
  - apiGroups: ["storage.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  # Batch
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]
  # Autoscaling
  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["*"]
  # Policy
  - apiGroups: ["policy"]
    resources: ["*"]
    verbs: ["*"]
  # RBAC (for managing roles within namespace)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["*"]

---
# RoleBinding to bind the service account to the role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-account-rolebinding
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: my-namespace
roleRef:
  kind: Role
  name: my-service-account-role
  apiGroup: rbac.authorization.k8s.io

---
# Secret for the service account token (optional - for older k8s versions)
apiVersion: v1
kind: Secret
metadata:
  name: my-service-account-token
  namespace: my-namespace
  annotations:
    kubernetes.io/service-account.name: my-service-account
type: kubernetes.io/service-account-token

---
# Example usage in a Pod
# apiVersion: v1
# kind: Pod
# metadata:
#   name: example-pod
#   namespace: my-namespace
# spec:
#   serviceAccountName: my-service-account
#   containers:
#   - name: example-container
#     image: nginx:latest
#     ports:
#     - containerPort: 80

---
# Example usage in a Deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: example-deployment
#   namespace: my-namespace
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: example-app
#   template:
#     metadata:
#       labels:
#         app: example-app
#     spec:
#       serviceAccountName: my-service-account
#       containers:
#       - name: example-container
#         image: nginx:latest
#         ports:
#         - containerPort: 80
