---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssl-example-com-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ssl-example-com"]
  verbs: ["get", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssl-example-com-reader-binding
subjects:
## can change to User
- kind: ServiceAccount
  name: my-serviceaccount
roleRef:
  kind: Role
  name: ssl-example-com-reader
  apiGroup: rbac.authorization.k8s.io


## the create the service account kubectl create serviceaccount my-serviceaccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-serviceaccount
      containers:
      - name: my-container
        image: my-image:latest
        # ...