---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nathapp-letsencrypt-prod
spec:
  acme:
    email: williamkhoo@nathapp.com
    preferredChain: ""
    privateKeySecretRef:
      name: cluster-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "nathapp.io"
      dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token
          email: williamkhoo@nathapp.com

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
type: Opaque
stringData:
  api-token: <API Token>

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-nathapp.io
spec:
  secretName: ssl-nathapp.io
  issuerRef:
    kind: ClusterIssuer
    name: nathapp-letsencrypt-prod
  commonName: nathapp.io
  dnsNames:
    - '*.nathapp.io'